---
- name: Create postgres user with specific right
  community.postgresql.postgresql_user:
    name: "{{ user_postgres }}"
    password: "{{ password }}"
    role_attr_flags: CREATEDB,NOCREATEROLE,NOSUPERUSER

- name: Grant user on the DB
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgresql_version.stdout}}/main/pg_hba.conf
    contype: host
    users: "{{user_postgres}}"
    databases: all
    method: md5
    source: "{% if odoo.development %}{% else %}{{ hostvars[odoo_hostname].ansible_default_ipv4.address }}{% endif %}"
    create: true
  notify: (Handler) Restart postgres
  when: not odoo.development
