---
- name: Create postgres user with specific right
  community.postgresql.postgresql_user:
    name: "{{odoo_user}}"
    password: "{{odoo_user_postgres_password}}"
    role_attr_flags: SUPERUSER
  become_user: postgres
  become: true

- name: Register postgresql_version
  ansible.builtin.shell: pg_config --version | awk -F'[. ]' '{print $2}'
  register: postgresql_version

- name: Grant user on the DB
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{postgresql_version.stdout}}/main/pg_hba.conf
    contype: local
    users: "{{odoo_user}}"
    databases: all
    method: md5
    create: true
  become_user: postgres
  become: true
  notify: restart postgres