---
- name: Configure user postgress
  block:
    - name: Create postgres user with specific right
      community.postgresql.postgresql_user:
        name: "{{odoo_user}}"
        password: "{{odoo_user_postgres_password}}"
        role_attr_flags: SUPERUSER

    - name: Register postgresql_version
      ansible.builtin.shell: pg_config --version | awk -F'[. ]' '{print $2}'
      register: postgresql_version

    - name: Grant user on the DB
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/{{postgresql_version.stdout}}/main/pg_hba.conf
        contype: host
        users: "{{odoo_user}}"
        databases: all
        method: md5
        source: "{{ hostvars[odoo_hostname].ansible_default_ipv4.address }}"
        create: true
      notify: restart postgres
      when: not development

    - name: Configure postgresql.conf Set listen_addresses.
      lineinfile: dest=/etc/postgresql/{{ postgresql_version.stdout }}/main/postgresql.conf
        regexp="listen_addresses =" line="listen_addresses = '*'" state=present
      notify: restart postgres
      when: not development
  become_user: postgres
  become: true