#---
- name: Install python version
  include_tasks : 00_0_check_python.yml
  loop: "{{ list_odoo_instance }}"
  loop_control:
    loop_var: odoo
  when: inventory_hostname in groups['odoo']

- name: Create postgres user for Odoo
  include_tasks : 01_0_postgres.yml
  loop: "{{ list_odoo_instance }}"
  loop_control:
    loop_var: odoo
  when: inventory_hostname in groups['postgres']

- name: deploy odoo
  include_tasks : 02_0_odoo_install.yml
  loop: "{{ list_odoo_instance }}"
  loop_control:
    loop_var: odoo
  when: inventory_hostname in groups['odoo']

- name: Add addons
  include_tasks : 10_0_addons.yml
  loop: "{{ list_odoo_instance }}"
  loop_control:
    loop_var: odoo
  when: inventory_hostname in groups['odoo']

- name: configure nginx
  include_tasks: nginx/main.yml
  loop: "{{ list_odoo_instance }}"
  loop_control:
    loop_var: odoo
  when: inventory_hostname in groups['nginx']
