---
# task file for 'deploy from scratch' of odoo

- name: Check if python3.8 is installed
  ansible.builtin.command: python3.8 --version
  register: python_version_output
  ignore_errors: true

- name: Install python3.8
  import_tasks: 00_odoo_python38.yml
  when: not python_version_output.stdout and odoo_version | int <= 14

# Create postgres user Odoo
- name: Execute odoo_postgres.yml
  import_tasks: 01_odoo_postgres.yml

# Install Odoo
#- name: Execute odoo_install.yml
#  import_tasks: 02_odoo_install.yml
