---
# task file for 'deploy from scratch' of odoo
- block:
  - name: create user
    ansible.builtin.user:
      name: "{{odoo_user}}"
      create_home: true
      home: "{{env_path}}"
      shell: /bin/bash

  - name: create etc directory
    file:
      path: "{{item}}"
      state: directory
      owner: "{{odoo_user}}"
      group: "{{odoo_user}}"
    loop:
      - "{{env_path}}/etc"
      - "{{env_path}}/data"
      - "{{env_path}}/addons"

  - name: Copy odoo.conf
    vars:
      admin_passwd: "{{ lookup('ansible.builtin.password', '/tmp/passwordfile length=8 chars=digits') }}"
    template:
      src: odoo.conf.j2
      owner: "{{odoo_user}}"
      group: "{{odoo_user}}"
      dest: "{{env_path}}/etc/odoo.conf"
      force: false

  - name: "apt installation"
    apt:
      update_cache: true
      name:
        - "git"
        - "virtualenv"
        - libsasl2-dev 
        - libldap2-dev 
        - libssl-dev
      state: "present"
    become: true

  - name: Clone odoo community repository
    git:
      repo: https://github.com/odoo/odoo.git
      dest: "{{env_path}}/odoo"
      version: "{{odoo_version}}.0"
      single_branch: "true"
      depth: 1

  - name: Create a list of dependencies
    shell:
      cmd: "/usr/bin/sed -n -e '/^Depends:/,/^Pre/ s/ python3-\\(.*\\),/python3-\\1/p' {{env_path}}/odoo/debian/control"
    register: list_dependance

  - name: Install apt dependencies 
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items: "{{ list_dependance['stdout_lines'] }}"

  - block:
    - name: Clone odoo template repository
      git:
        repo: git@github.com:odoo/design-themes.git
        dest: "{{env_path}}/addons/design-themes"
        clone: true
        update: true
        version: "{{odoo_version}}.0"
        single_branch: "true"
        depth: 1

    - name: Clone odoo enterprise repository
      git:
        repo: git@github.com:odoo/enterprise.git
        dest: "{{env_path}}/addons/enterprise"
        clone: true
        update: true
        version: "{{odoo_version}}.0"
        single_branch: "true"
        depth: 1
    when: enterprise

  - name: Install pip pre-dependencies
    pip:
      name:
        - setuptools
        - wheel
      virtualenv: "{{env_path}}/venv"
      virtualenv_python: "python3"
    become_user: "{{odoo_user}}"
    become: true

  - name: Install odoo python dependencies
    pip:
      requirements: "{{env_path}}/odoo/requirements.txt"
      virtualenv: "{{env_path}}/venv"
      virtualenv_python: "python3"
    become_user: "{{odoo_user}}"
    become: true

  - block:
    - name: Clone odoo stub repository for development purpose
      git:
        repo: https://github.com/odoo-ide/odoo-stubs.git
        dest: "{{env_path}}/odoo-stubs"
        clone: true
        update: true
        version: "{{odoo_version}}.0"
        single_branch: "true"
        depth: 1
    when: development


  - block:
    - name: Create odoo service
      template:
        src: odoo.service.j2
        owner: "{{odoo_user}}"
        group: "{{odoo_user}}"
        dest: "/etc/systemd/system/{{odoo_user}}.service"
        force: false

    - name: Enable Odoo service
      service:
        name: "{{odoo_user}}"
        state: started
        enabled: true
    when: not development
  become: true
