---
# task file for 'deploy from scratch' of odoo
- name: Execute odoo_postgres.yml
  import_tasks: 01_odoo_postgres.yml
  when: inventory_hostname in groups['postgres']

- name: Execute odoo_postgres.yml
  import_tasks: 02_odoo_install.yml
  when: inventory_hostname in groups['odoo']