#odoo_version: "16"
#development: false
#enterprise: false
#odoo_user: "odoo{{odoo_version}}"
#linux_user: "{% if development %}false{% else %}{{ odoo_user }}{% endif %}"
#
#postgres_user: "{{ linux_user }}"
#postgres_user_password: "{{ lookup('ansible.builtin.password', '/tmp/passwordfile length=16 chars=ascii_letters,digits,!@#$%^&*()_+') }}"
#postgres_address: false
postgres_hostname: false
