#odoo_version: "16"
#development: false
#enterprise: false
#odoo_user: "odoo{{odoo_version}}"
#linux_user: "{% if development %}false{% else %}{{ odoo_user }}{% endif %}"
#
#postgres_user: "{{ linux_user }}"
#postgres_user_password: "{{ lookup('ansible.builtin.password', '/tmp/passwordfile length=16 chars=ascii_letters,digits,!@#$%^&*()_+') }}"
#postgres_address: false
postgres_hostname: false
default_odoo_ports:
  production:
    odoo_port: 69
    longpolling_port: 72
  stage:
    odoo_port: 70
    longpolling_port: 71
  manager:
    odoo_port: 68
    longpolling_port: 73
